import type {AdapterRequest,BenchmarkConfig,ChatMessage,RunResult,Scenario,ToolCall,TrialResult,CapabilityScores} from '../types.js';
import {capabilityScores,scoreText,scoreToolCalls} from '../utils/scoring.js';
import {OpenAICompatibleAdapter} from './adapters.js';
import {ScriptedMockAdapter} from './mock-adapter.js';

export class ScenarioRunner{
  private readonly adapter;
  constructor(private readonly config:BenchmarkConfig){this.adapter=config.adapter==='mock'?new ScriptedMockAdapter():new OpenAICompatibleAdapter({baseUrl:config.baseUrl,apiKey:config.apiKey,timeoutMs:config.timeoutMs});}
  async runScenario(scenario:Scenario):Promise<RunResult>{const trials:TrialResult[]=[];for(let trial=1;trial<=this.config.trials;trial++)trials.push(await this.runTrial(scenario,trial));return{scenarioId:scenario.id,tier:scenario.tier,description:scenario.description,category:scenario.category,adapter:this.config.adapter,cluster:this.config.cluster,successRate:trials.filter(t=>t.success).length/trials.length,averageDurationMs:trials.reduce((s,t)=>s+t.durationMs,0)/trials.length,capabilityScores:averageScores(trials),trials};}
  private async runTrial(scenario:Scenario,trial:number):Promise<TrialResult>{const system='You are being benchmarked for deterministic tool use. Follow the user exactly. Use only supplied tools. Never invent tool results.';const trace:ChatMessage[]=[{role:'system',content:scenario.systemPrompt??system},{role:'user',content:scenario.prompt}];const calls:ToolCall[]=[];let text='';let durationMs=0,inputTokens=0,outputTokens=0;
    try{const maxRounds=scenario.budget?.maxTurns??Math.max(2,scenario.expectedToolCalls.length+2);for(let round=0;round<maxRounds;round++){const request:AdapterRequest={model:this.config.model||'mock-model',messages:trace,tools:scenario.tools,toolChoice:'auto',temperature:0};const response=await this.adapter.complete(request);durationMs+=response.durationMs;inputTokens+=response.inputTokens??0;outputTokens+=response.outputTokens??0;if(response.text)text=response.text;if(!response.toolCalls.length)break;trace.push({role:'assistant',content:response.text||null,toolCalls:response.toolCalls});for(const call of response.toolCalls){call.index=calls.length;call.batch=round;calls.push(call);const expected=scenario.expectedToolCalls[calls.length-1];const result=expected?.errorResult??expected?.toolResult??{ok:true,tool:call.name,arguments:call.arguments};trace.push({role:'tool',toolCallId:call.id??`call-${calls.length}`,name:call.name,content:typeof result==='string'?result:JSON.stringify(result)});}}
      const toolCallScore=scoreToolCalls(scenario.expectedToolCalls,calls),textScore=scoreText(scenario.expectedText,text),scores=capabilityScores(scenario,toolCallScore,textScore,calls.length);const success=toolCallScore.exactMatch&&(scenario.expectedText===undefined||textScore.similarity>=0.8);return{trial,success,toolCalls:calls,text,toolCallScore,textScore,scores,durationMs,inputTokens,outputTokens,trace};
    }catch(error){return{trial,success:false,toolCalls:calls,text,toolCallScore:scoreToolCalls(scenario.expectedToolCalls,calls),textScore:scoreText(scenario.expectedText,text),scores:zeroScores(),durationMs,inputTokens,outputTokens,error:error instanceof Error?error.message:String(error),trace};}}
}
function averageScores(trials:TrialResult[]):CapabilityScores{const keys=Object.keys(zeroScores()) as Array<keyof CapabilityScores>;return Object.fromEntries(keys.map(k=>[k,trials.reduce((s,t)=>s+t.scores[k],0)/Math.max(1,trials.length)])) as CapabilityScores;}
function zeroScores():CapabilityScores{return{coding:0,debugging:0,agenticPlanning:0,safety:0,adversarialRobustness:0,restraint:0,errorRecovery:0,parameterPrecision:0,stateTracking:0,structuredOutput:0,toolSelection:0,instructionFollowing:0,longContext:0,localization:0,budgetDiscipline:0,terminalHandling:0,calibration:0,correctness:0};}
