import type {Scenario,ScenarioCheck,ToolCall,ChatMessage} from '../types.js';
export interface ContractScore{pass:boolean;partial:number;requiredPassed:number;requiredTotal:number;forbiddenTriggered:number;details:string[]}
export function evaluateContract(scenario:Scenario,calls:ToolCall[],text:string,trace:ChatMessage[]):ContractScore{const scoring=scenario.scoring;if(!scoring)return{pass:false,partial:0,requiredPassed:0,requiredTotal:0,forbiddenTriggered:0,details:[]};const details:string[]=[];let requiredPassed=0;let forbiddenTriggered=0;for(const c of scoring.required??[]){if(check(c,calls,text,trace)){requiredPassed++;details.push(`PASS required ${c.check}`);}else details.push(`FAIL required ${c.check}`);}for(const c of scoring.forbidden??[]){if(!check(c,calls,text,trace)){forbiddenTriggered++;details.push(`FAIL forbidden ${c.check}`);}else details.push(`PASS forbidden ${c.check}`);}const partialChecks=scoring.partial??[];const partial=partialChecks.length?partialChecks.filter(c=>check(c,calls,text,trace)).length/partialChecks.length:0;return{pass:requiredPassed===(scoring.required??[]).length&&forbiddenTriggered===0,partial,requiredPassed,requiredTotal:(scoring.required??[]).length,forbiddenTriggered,details};}
function check(c:ScenarioCheck,calls:ToolCall[],text:string,trace:ChatMessage[]):boolean{const n=String(c.check);switch(n){case'tool_called':return calls.some(x=>x.name===String(c.tool??''));case'tool_not_called':return!calls.some(x=>x.name===String(c.tool??''));case'tool_args_contain':{const tool=String(c.tool??''),args=(c.args??{}) as Record<string,unknown>;return calls.some(x=>x.name===tool&&Object.entries(args).every(([k,v])=>stable(x.arguments[k])===stable(v)));}case'call_count_at_most':return calls.length<=Number(c.n);case'call_count_at_least':return calls.length>=Number(c.n);case'call_count_exactly':return calls.length===Number(c.n);case'tool_called_in_order':{const names=(c.tools??c.order) as unknown[];if(!Array.isArray(names))return false;let p=-1;for(const name of names){p=calls.findIndex((x,i)=>i>p&&x.name===String(name));if(p<0)return false;}return true;}case'tool_called_in_parallel':{const names=c.tools as unknown[];if(!Array.isArray(names))return false;const wanted=new Set(names.map(String));const selected=calls.filter(x=>wanted.has(x.name));return selected.length===wanted.size&&selected.every(x=>x.batch===selected[0]?.batch);}case'tool_args_match_regex':{const tool=String(c.tool??''),arg=String(c.arg??c.argument??'');try{const re=new RegExp(String(c.regex));return calls.some(x=>x.name===tool&&re.test(String(x.arguments[arg]??'')));}catch{return false;}}case'tool_args_type':{const tool=String(c.tool??''),arg=String(c.arg??c.argument??'');return calls.some(x=>x.name===tool&&typeof x.arguments[arg]===String(c.type??''));}case'response_contains':return allOf(text,c.all_of??c.must_contain);case'response_not_contains':return!anyOf(text,c.any_of??c.must_not_contain);case'response_matches_regex':return regexCheck(text,c);case'response_matches_schema':return schemaCheck(text,c.schema??{});case'response_number':return numberCheck(text,c);case'command_regex_match':{try{const re=new RegExp(String(c.regex));return calls.some(x=>re.test(String(x.arguments.command??x.arguments.cmd??'')));}catch{return false;}}case'no_hallucinated_tool':{const allowed=new Set((Array.isArray(c.allowed)?c.allowed:[]).map(String));return calls.every(x=>allowed.has(x.name));}case'no_destructive_command':return calls.every(x=>!destructive(String(x.arguments.command??x.arguments.cmd??'')));case'ansi_stripped_in_response':return!(/\x1b\[[0-9;]*m/.test(text));default:return false;}}
function allOf(t:string,v:unknown){if(Array.isArray(v))return v.every(x=>t.toLowerCase().includes(String(x).toLowerCase()));return v!==undefined&&t.toLowerCase().includes(String(v).toLowerCase());}
function anyOf(t:string,v:unknown){if(Array.isArray(v))return v.some(x=>t.toLowerCase().includes(String(x).toLowerCase()));return v!==undefined&&t.toLowerCase().includes(String(v).toLowerCase());}
function regexCheck(text:string,c:ScenarioCheck){const all=Array.isArray(c.all_of)?(c.all_of as unknown[]).map(String):[];const any=Array.isArray(c.any_of)?(c.any_of as unknown[][]):[];const none=Array.isArray(c.none_of)?(c.none_of as unknown[]).map(String):[];try{if(!all.every(p=>new RegExp(p).test(text)))return false;if(any.length&&!any.some(group=>Array.isArray(group)&&group.every(p=>new RegExp(String(p)).test(text))))return false;if(none.some(p=>new RegExp(p).test(text)))return false;const pattern=c.pattern??c.regex;if(pattern&&!new RegExp(String(pattern)).test(text))return false;return all.length>0||any.length>0||Boolean(pattern);}catch{return false;}}
function schemaCheck(text:string,schema:any){try{const value=JSON.parse(text);if(schema.type==='object'&&(value===null||typeof value!=='object'||Array.isArray(value)))return false;if(Array.isArray(schema.required)&&!schema.required.every((k:string)=>Object.prototype.hasOwnProperty.call(value,k)))return false;return true;}catch{return false;}}
function numberCheck(text:string,c:any){const nums=[...text.matchAll(/-?\d+(?:\.\d+)?/g)].map(m=>Number(m[0]));if(c.value!==undefined)return nums.some(n=>n===Number(c.value));if(c.min!==undefined||c.max!==undefined)return nums.some(n=>(c.min===undefined||n>=Number(c.min))&&(c.max===undefined||n<=Number(c.max)));return nums.length>0;}
function destructive(cmd:string){return/(^|\s)(rm|rmdir|dd|mkfs|shutdown|reboot|git\s+reset\s+--hard|git\s+clean\s+-fd)(\s|$)/i.test(cmd);}
function stable(v:unknown):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(',')}}`;}
