import type {BenchmarkSummary,CapabilityScores,ExpectedToolCall,Scenario,TextScore,ToolCall,ToolCallScore} from '../types.js';
import {DIMENSIONS} from '../dimensions.js';
const CAPS=Object.keys({coding:0,debugging:0,agenticPlanning:0,safety:0,adversarialRobustness:0,restraint:0,errorRecovery:0,parameterPrecision:0,stateTracking:0,structuredOutput:0,toolSelection:0,instructionFollowing:0,longContext:0,localization:0,budgetDiscipline:0,terminalHandling:0,calibration:0,correctness:0}) as Array<keyof CapabilityScores>;
function stable(v:unknown):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(',')}}`;}
function argAccuracy(expected:Record<string,unknown>,actual:Record<string,unknown>):number{const keys=Object.keys(expected);if(!keys.length)return Object.keys(actual).length?0:1;return keys.filter(k=>stable(expected[k])===stable(actual[k])).length/keys.length;}
export function scoreToolCalls(expected:ExpectedToolCall[],actual:ToolCall[]):ToolCallScore{const used=new Set<number>();let matches=0,args=0;for(const call of actual){const i=expected.findIndex((e,n)=>!used.has(n)&&e.name===call.name);if(i>=0){used.add(i);matches++;args+=argAccuracy(expected[i].arguments,call.arguments);}}const precision=actual.length?matches/actual.length:expected.length?0:1;const recall=expected.length?matches/expected.length:actual.length?0:1;const f1=precision+recall?2*precision*recall/(precision+recall):0;const exactMatch=expected.length===actual.length&&expected.every((e,i)=>e.name===actual[i]?.name&&stable(e.arguments)===stable(actual[i]?.arguments));return{precision,recall,f1,exactMatch,missing:expected.filter((_,i)=>!used.has(i)),extra:actual.filter(c=>!expected.some(e=>e.name===c.name)),argumentAccuracy:matches?args/matches:0};}
export function scoreText(expected:string|undefined,actual:string):TextScore{if(expected===undefined||expected===actual)return{exactMatch:true,similarity:1};const a=new Set(expected.toLowerCase().split(/\W+/).filter(Boolean));const b=new Set(actual.toLowerCase().split(/\W+/).filter(Boolean));const union=new Set([...a,...b]).size;const intersection=[...a].filter(x=>b.has(x)).length;return{exactMatch:false,similarity:union?intersection/union:1};}
export function capabilityScores(scenario:Scenario,tool:ToolCallScore,text:TextScore,actualCount:number):CapabilityScores{const base:CapabilityScores={coding:tool.f1,debugging:tool.f1,agenticPlanning:tool.f1,safety:text.similarity,adversarialRobustness:tool.f1,restraint:actualCount<=scenario.expectedToolCalls.length?1:Math.max(0,scenario.expectedToolCalls.length/Math.max(actualCount,1)),errorRecovery:tool.recall,parameterPrecision:tool.argumentAccuracy,stateTracking:tool.f1,structuredOutput:text.similarity,toolSelection:tool.f1,instructionFollowing:text.similarity,longContext:tool.f1,localization:tool.argumentAccuracy,budgetDiscipline:restraintBudget(scenario,actualCount),terminalHandling:tool.f1,calibration:text.similarity,correctness:(tool.f1+text.similarity)/2};
  const active=new Set(scenario.capabilities as string[]);for(const dim of DIMENSIONS){if(!active.has(dim))base[dim]=Math.max(0,base[dim]);}return base;}
function restraintBudget(scenario:Scenario,count:number):number{const max=scenario.budget?.maxToolCalls;return max===undefined?1:count<=max?1:Math.max(0,max/Math.max(1,count));}
export function aggregateSummary(results:{success:boolean;durationMs:number;scores:CapabilityScores}[],scenarioCount:number,profile:string,benchmarkVersion:string):BenchmarkSummary{const trials=results.length,passedTrials=results.filter(r=>r.success).length;const capabilityScores=Object.fromEntries(CAPS.map(cap=>[cap,trials?results.reduce((s,r)=>s+r.scores[cap],0)/trials:0])) as unknown as CapabilityScores;return{benchmarkVersion,scenarios:scenarioCount,trials,passedTrials,successRate:trials?passedTrials/trials:0,averageDurationMs:trials?results.reduce((s,r)=>s+r.durationMs,0)/trials:0,capabilityScores,profile};}
