import React,{useState,useMemo}from'react';
import{Box,Text,useApp,useInput,Spacer}from'ink';
import type{BenchmarkConfig,BenchmarkSummary,RunResult,TrialResult,CapabilityName}from'./types.js';
import{loadScenarios}from'./scenarios.js';
import{BenchmarkService}from'./benchmark.js';
import{PROFILES}from'./profiles.js';
import{formatSummary}from'./export.js';
import{appendHistory,loadHistory}from'./history.js';
import{buildRanking}from'./rankings.js';

const TABS=['Home','Scenarios','Run','Results','Rankings','Compare','Profiles','History','Settings']as const;
type Tab=typeof TABS[number];
const CAPABILITIES:CapabilityName[]=['agenticPlanning','parameterPrecision','stateTracking','instructionFollowing','restraint','errorRecovery','calibration','correctness'];
const SETTING_FIELDS=[{id:'model',label:'Model',type:'text'},{id:'baseUrl',label:'Base URL',type:'text'},{id:'adapter',label:'Adapter',type:'select',options:['openai-compatible','raw','mock','cloud','hermes']},{id:'source',label:'Source',type:'select',options:['synthetic','upstream']},{id:'tier',label:'Tier',type:'select',options:['all','easy','medium','hard','very-hard']},{id:'trials',label:'Trials',type:'number',min:1,max:100},{id:'concurrency',label:'Concurrency',type:'number',min:1,max:32}] as const;

export function App({config}:{config:BenchmarkConfig}){
 const{exit}=useApp();
 const[tab,setTab]=useState<Tab>('Home');
 const[cfg,setCfg]=useState<BenchmarkConfig>(config);
 const[sfocus,setSfocus]=useState(0);const[editing,setEditing]=useState(false);const[editVal,setEditVal]=useState('');
 const scenarios=useMemo(()=>{process.env.TOOLERY_SOURCE=cfg.source;const s=loadScenarios(cfg.tier==='all'?undefined:cfg.tier as any);return cfg.category?s.filter((x:any)=>x.category===cfg.category):s},[cfg.source,cfg.tier,cfg.category]);
 const[results,setResults]=useState<RunResult[]>([]);const[running,setRunning]=useState(false);const[completed,setCompleted]=useState(0);const[error,setError]=useState<string>();const[history,setHistory]=useState<any[]>([]);const[summary,setSummary]=useState<BenchmarkSummary>();const[activeScenario,setActiveScenario]=useState<string>();
 useInput((input,key)=>{
  if(input==='q'){exit();return}
  if(key.escape){if(editing){setEditing(false);return}if(tab==='Settings'){setTab('Home');return}exit();return}
  if(tab==='Settings'){
    if(editing){
      if(key.return){const f=SETTING_FIELDS[sfocus];setCfg(c=>({...c,[f.id]:f.type==='number'?Math.max((f as any).min,Math.min((f as any).max,Number(editVal)||0)):editVal}));setEditing(false);return}
      if(key.backspace||key.delete){setEditVal(v=>v.slice(0,-1));return}
      if(input&&input.length===1)setEditVal(v=>v+input);
      return
    }
    if(key.upArrow){setSfocus(i=>(i-1+SETTING_FIELDS.length)%SETTING_FIELDS.length);return}
    if(key.downArrow){setSfocus(i=>(i+1)%SETTING_FIELDS.length);return}
    if(key.return){const f=SETTING_FIELDS[sfocus];if(f.type==='text'){setEditVal(String((cfg as any)[f.id]??''));setEditing(true);return}}
    if(key.leftArrow||key.rightArrow){
      const f=SETTING_FIELDS[sfocus];const dir=key.rightArrow?1:-1;
      if(f.type==='select'){const opts=[...(f as any).options]as string[];const cur=opts.indexOf(String((cfg as any)[f.id]));setCfg(c=>({...c,[f.id]:opts[(cur+dir+opts.length)%opts.length]}));return}
      if(f.type==='number'){const{min,max}=f as any;setCfg(c=>({...c,[f.id]:Math.min(max,Math.max(min,Number((c as any)[f.id])+dir))}));return}
      move(dir);return
    }
    if(input==='r'&&!running)void run();
    return
  }
  if(key.leftArrow)move(-1);if(key.rightArrow)move(1);if(input==='r'&&!running)void run()
 });
 function move(delta:number){const i=TABS.indexOf(tab);setTab(TABS[(i+delta+TABS.length)%TABS.length])}
 async function run(){setRunning(true);setResults([]);setCompleted(0);setError(undefined);setSummary(undefined);try{const service=new BenchmarkService(cfg);const result=await service.run(scenarios,(count,_total,item)=>{setCompleted(count);setActiveScenario(item.scenarioId);setResults(p=>[...p,item])});setResults(result.results);setSummary(result.summary);setActiveScenario(result.results.at(-1)?.scenarioId);const runId=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;await appendHistory({runId,startedAt:new Date().toISOString(),model:cfg.model,adapter:cfg.adapter,source:cfg.source,tier:cfg.tier,profile:cfg.profile,cluster:cfg.cluster,summary:result.summary,results:result.results});setHistory(await loadHistory())}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRunning(false)}}
 const ranking=buildRanking(cfg.model||'(unknown)',cfg.adapter,cfg.cluster??'single',results);const current=results.at(-1);const scenario=scenarios.find(s=>s.id===activeScenario)??scenarios[completed]??scenarios[0];
 return <Box flexDirection="column"padding={1}width={150}><Header config={cfg}running={running}/><TabBar tab={tab}/>{error&&<Box borderStyle="round"borderColor="red"paddingX={1}><Text color="red">ERROR  {error}</Text></Box>}{tab==='Home'&&<Home config={cfg}scenarios={scenarios}results={results}summary={summary}running={running}current={current}scenario={scenario}/>}{tab==='Scenarios'&&<ScenarioList scenarios={scenarios}results={results}active={activeScenario}/>}{tab==='Run'&&<RunView config={cfg}scenario={scenario}current={current}running={running}completed={completed}total={scenarios.length}/>}{tab==='Results'&&<ResultsView results={results}summary={summary}/>}{tab==='Rankings'&&<Rankings ranking={ranking}/>}{tab==='Compare'&&<Compare results={results}/>}{tab==='Profiles'&&<Profiles/>}{tab==='History'&&<History items={history}/>}{tab==='Settings'&&<Settings cfg={cfg}sfocus={sfocus}editing={editing}editVal={editVal}/>}<Footer tab={tab}editing={editing}/></Box>
}
function Header({config,running}:{config:BenchmarkConfig;running:boolean}){return <Box borderStyle="round"paddingX={2}flexDirection="column"><Box><Text bold color="cyan">🔧 Toolery-TS</Text><Text>  ·  Deterministic tool-calling benchmark for LLM endpoints</Text><Spacer/><Text color="green">● {running?'RUNNING':'READY'}</Text></Box><Box><Text dimColor>v{config.benchmarkVersion}   </Text><Text color="gray">Model:</Text><Text> {config.model||'(endpoint default)'} </Text><Text color="gray">Adapter:</Text><Text> {config.adapter}</Text><Spacer/><Text dimColor>{config.baseUrl}</Text></Box></Box>}
function TabBar({tab}:{tab:Tab}){return <Box marginTop={1}borderStyle="single"paddingX={1}>{TABS.map(t=><Box key={t}paddingX={1}><Text bold={t===tab}color={t===tab?'cyan':undefined}>{t===tab?'[ '+t+' ]':t}</Text></Box>)}</Box>}
function Home({config,scenarios,results,summary,running,current,scenario}:{config:BenchmarkConfig;scenarios:any[];results:RunResult[];summary?:BenchmarkSummary;running:boolean;current?:RunResult;scenario:any}){const completed=results.length;const pct=scenarios.length?Math.round(completed/scenarios.length*100):0;return <Box marginTop={1}><Box width="31%"flexDirection="column"><Panel title="⚙ Configuration"><KV k="Model"v={config.model||'(endpoint default)'}/><KV k="Base URL"v={config.baseUrl}/><KV k="Adapter"v={config.adapter}/><KV k="Tier"v={`${config.tier} (${scenarios.length} scenarios)`}/><KV k="Trials"v={String(config.trials)}/><KV k="Concurrency"v={String(config.concurrency)}/><KV k="Source"v={config.source}/><KV k="Cluster"v={config.cluster??'single'}/><Box marginTop={1}><Text color="green">✓ Endpoint configured</Text></Box></Panel><Panel title="▶ Benchmark Progress"><Progress value={pct}/><Text>{completed} / {scenarios.length} ({pct}%)</Text><Box marginTop={1}flexDirection="column"><KV k="Current"v={scenario?.id??'—'}/><KV k="Category"v={scenario?.category??'—'}/><KV k="Status"v={running?'Running...':summary?'Complete':'Ready'}/></Box></Panel><Panel title="⚡ Quick Actions"><KV k="r"v="Start benchmark"/><KV k="→ / ←"v="Switch tab"/><KV k="q"v="Quit"/><KV k="Esc"v="Quit"/></Panel></Box><Box width="69%"marginLeft={1}flexDirection="column"><LivePanel scenario={scenario}current={current}running={running}/><Box alignItems="flex-start"><ResultPanel result={current}/><CapabilityPanel result={current}summary={summary}/></Box><RecentPanel results={results}/></Box></Box>}
function RunView({config,scenario,current,running,completed,total}:{config:BenchmarkConfig;scenario:any;current?:RunResult;running:boolean;completed:number;total:number}){return <Box marginTop={1}flexDirection="column"><LivePanel scenario={scenario}current={current}running={running}/><Box marginTop={1}><Panel title="Run configuration"><KV k="Model"v={config.model||'(endpoint default)'}/><KV k="Adapter"v={config.adapter}/><KV k="Trials"v={String(config.trials)}/><KV k="Concurrency"v={String(config.concurrency)}/><KV k="Progress"v={`${completed} / ${total}`}/></Panel><TracePanel trial={current?.trials.at(-1)}/></Box></Box>}
function LivePanel({scenario,current,running}:{scenario:any;current?:RunResult;running:boolean}){return <Panel title={`▣ Live Run · ${scenario?.id??'—'}`}right={running?'Running...':'READY'}rightColor={running?'yellow':'green'}><Text>{scenario?.description??scenario?.prompt??'Ready to run benchmark.'}</Text><TracePanel trial={current?.trials.at(-1)}compact/></Panel>}
function TracePanel({trial,compact=false}:{trial?:TrialResult;compact?:boolean}){if(!trial)return <Box marginTop={1}><Text dimColor>No tool trace yet. Press [r] to start a benchmark.</Text></Box>;if(trial.error)return <Box marginTop={1}flexDirection="column"><Text bold color="red">✗ Error</Text><Box borderStyle="single"paddingX={1}><Text color="red">{trial.error}</Text></Box></Box>;return <Box marginTop={1}flexDirection="column"><Text bold color="cyan">● Conversation</Text><Box borderStyle="single"flexDirection="column"paddingX={1}>{(trial.trace??[]).slice(compact?-8:0).map((m,i)=><Box key={`${m.role}-${i}`}><Cell width={compact?18:22}bold color={m.role==='tool'?'green':m.role==='assistant'?'magenta':m.role==='user'?'white':'gray'}>{m.role.toUpperCase()}</Cell><Text>{String(m.content??(m.toolCalls?.map(c=>`${c.name}(${JSON.stringify(c.arguments)})`).join(', ')??''))}</Text></Box>)}</Box></Box>}
function ResultPanel({result}:{result?:RunResult}){const t=result?.trials.at(-1);return <Box width="52%"><Panel title="✓ Scenario Result"right={t?.success?'PASS':t?.error?'ERROR':'—'}rightColor={t?.success?'green':t?.error?'red':'gray'}>{t?<><KV k="Tool Calls"v={`${t.toolCalls.length} observed`}/><KV k="Arguments"v={`${(t.toolCallScore.argumentAccuracy*100).toFixed(0)}% correct`}/><KV k="Response"v={`${t.textScore.similarity.toFixed(2)} similarity`}/><KV k="Duration"v={`${(t.durationMs/1000).toFixed(1)}s`}/><KV k="Tokens"v={t.inputTokens&&t.outputTokens?`${t.inputTokens+t.outputTokens}`:'—'}/>{t.error&&<KV k="Error"v={t.error}/>}</>:<Text dimColor>No completed scenario.</Text>}</Panel></Box>}
function CapabilityPanel({result,summary}:{result?:RunResult;summary?:BenchmarkSummary}){const scores=result?.capabilityScores??summary?.capabilityScores;return <Box width="48%"marginLeft={1}><Panel title="▥ Capability Scores">{CAPABILITIES.map(k=><Score key={k}name={k}value={Number(scores?.[k]??0)}/>)}</Panel></Box>}
function Score({name,value}:{name:string;value:number}){const width=14;const filled=Math.max(0,Math.min(width,Math.round(value*width)));return <Box><Cell width={24}>{name}</Cell><Text color={value>=.8?'green':value>=.6?'yellow':'red'}>{'█'.repeat(filled)}{'░'.repeat(width-filled)}</Text><Text> {(value*100).toFixed(0)}%</Text></Box>}
function RecentPanel({results}:{results:RunResult[]}){return <Panel title="▤ Recent Scenarios"marginTop={1}><Box><Cell width={5}>#</Cell><Cell width={18}>ID</Cell><Cell width={10}>Tier</Cell><Cell width={20}>Category</Cell><Cell width={12}>Status</Cell><Cell width={12}>Calls</Cell><Cell width={10}>Score</Cell><Text>Duration</Text></Box>{results.slice(-6).map((r,i)=>{const t=r.trials.at(-1);return <Box key={r.scenarioId}><Cell width={5}>{results.length-5+i}</Cell><Cell width={18}color="cyan">{r.scenarioId}</Cell><Cell width={10}>{r.tier}</Cell><Cell width={20}>{r.category??'—'}</Cell><Cell width={12}color={t?.success?'green':t?.error?'red':'yellow'}>{t?.success?'✓ Pass':t?.error?'✗ Err':'○ Done'}</Cell><Cell width={12}>{t?`${t.toolCalls.length} calls`:'—'}</Cell><Cell width={10}>{t?(t.success?'PASS':'FAIL'):'—'}</Cell><Text>{t?`${(t.durationMs/1000).toFixed(1)}s`:'—'}</Text></Box>})}</Panel>}
function ScenarioList({scenarios,results,active}:{scenarios:any[];results:RunResult[];active?:string}){return <Panel title={`Scenarios · ${scenarios.length}`}marginTop={1}>{scenarios.slice(0,30).map((s,i)=>{const r=results.find(x=>x.scenarioId===s.id);return <Box key={s.id}><Cell width={5}>{i+1}</Cell><Cell width={18}color={s.id===active?'cyan':undefined}>{s.id}</Cell><Cell width={12}>{s.tier}</Cell><Cell width={24}>{s.category}</Cell><Text>{r?(r.trials.at(-1)?.success?'✓ PASS':'✗ FAIL'):'○ PENDING'}</Text></Box>})}{scenarios.length>30&&<Text dimColor>… {scenarios.length-30} more</Text>}</Panel>}
function ResultsView({results,summary}:{results:RunResult[];summary?:BenchmarkSummary}){return <Box marginTop={1}flexDirection="column"><Panel title="Benchmark Results">{summary&&<Text bold color="cyan">{formatSummary(summary)}</Text>}<Text>Completed scenarios: {results.length}</Text></Panel>{results.slice(-8).reverse().map(r=><ResultPanel key={r.scenarioId}result={r}/>)}</Box>}
function Rankings({ranking}:{ranking:any}){return <Box marginTop={1}flexDirection="column"><Panel title="Rankings"><Text bold>Score {(ranking.score*100).toFixed(1)}%</Text>{Object.entries(ranking.dimensions).map(([k,v])=><Score key={k}name={k}value={Number(v)}/>)}</Panel></Box>}
function Compare({results}:{results:RunResult[]}){return <Box marginTop={1}><Panel title="Paired comparison"><Text>Current run scenarios: {results.length}</Text><Text dimColor>Use compareRuns() with two saved result sets for exact paired McNemar analysis.</Text></Panel></Box>}
function Profiles(){return <Box marginTop={1}><Panel title="Benchmark Profiles">{PROFILES.map(p=><Box key={p.id}><Cell width={20}bold>{p.id}</Cell><Text>{p.description}</Text></Box>)}</Panel></Box>}
function History({items}:{items:any[]}){return <Box marginTop={1}><Panel title="Run History">{items.slice(-15).reverse().map(x=><Box key={x.runId}><Cell width={28}>{x.startedAt}</Cell><Cell width={22}>{x.model||'(unknown)'}</Cell><Text>{(Number(x.summary?.successRate??0)*100).toFixed(1)}%</Text></Box>)}{!items.length&&<Text dimColor>No history yet.</Text>}</Panel></Box>}
function Settings({config}:{config:BenchmarkConfig}){return <Box marginTop={1}><Panel title="Settings"><KV k="Benchmark version"v={config.benchmarkVersion}/><KV k="Timeout"v={`${config.timeoutMs}ms`}/><KV k="Endpoint path"v={config.endpointPath}/><KV k="Source"v={config.source}/><KV k="Performance checks"v={config.withPerf?'enabled':'disabled'}/></Panel></Box>}
function Panel({title,children,marginTop,right,rightColor}:{title:string;children:React.ReactNode;marginTop?:number;right?:string;rightColor?:'green'|'yellow'|'red'|'gray'}){return <Box borderStyle="round"paddingX={1}marginTop={marginTop??0}flexDirection="column"><Box><Text bold color="cyan">{title}</Text><Spacer/>{right&&<Text color={rightColor}>{right}</Text>}</Box>{children}</Box>}
function KV({k,v}:{k:string;v:string}){return <Box><Cell width={20}color="gray">{k}</Cell><Text>{v}</Text></Box>}
function Cell({children,width,color,bold}:{children:React.ReactNode;width:number;color?:'black'|'red'|'green'|'yellow'|'blue'|'magenta'|'cyan'|'white'|'gray';bold?:boolean}){return <Box width={width}flexShrink={0}><Text color={color}bold={bold}>{children}</Text></Box>}
function Progress({value}:{value:number}){const width=28;const filled=Math.max(0,Math.min(width,Math.round(value/100*width)));return <Box><Text color="green">{'█'.repeat(filled)}</Text><Text color="gray">{'░'.repeat(width-filled)}</Text><Text> {value}%</Text></Box>}
function Footer(){return <Box marginTop={1}borderStyle="single"paddingX={1}><Text dimColor>↑/↓ navigate   Enter select   ←/→ tabs   r run   ? help   q quit</Text><Spacer/><Text dimColor>143 scenarios · 18 capability dimensions · deterministic scoring</Text></Box>}
