import {readFile,readdir} from 'node:fs/promises';
import {existsSync,readFileSync as readSync} from 'node:fs';
import path from 'node:path';
import yaml from 'yaml';
import {toolByName} from './tool-catalog.js';
import type {CapabilityName,Dimension,JsonSchema,Scenario,ToolDefinition} from './types.js';
export const UPSTREAM_SOURCE='karolpalys/toolery@36c8c0c217898aade7500fa13b02fdc4d58899f7';
const CAPABILITY_MAP:Record<string,CapabilityName[]>={tool_selection:['toolSelection'],parameter_precision:['parameterPrecision'],multi_step_chains:['agenticPlanning'],restraint_refusal:['restraint'],error_recovery:['errorRecovery'],structured_reasoning:['agenticPlanning'],instruction_following:['instructionFollowing'],context_state_tracking:['stateTracking'],coding:['coding'],debugging:['debugging'],safety_boundaries:['safety'],adversarial_robustness:['adversarialRobustness'],toolset_scale:['toolSelection'],autonomous_planning:['agenticPlanning'],creative_composition:['structuredOutput'],structured_output:['structuredOutput'],hallucination:['calibration','correctness'],terminal_handling:['terminalHandling']};
function schema():JsonSchema{return{type:'object',properties:{},additionalProperties:true};}
function toolDefinitions(names:unknown):ToolDefinition[]{return(Array.isArray(names)?names:[]).map(name=>{const n=String(name);return toolByName.get(n)??{name:n,description:`Upstream Toolery fixture tool: ${n}.`,parameters:schema()};});}
function capabilities(category:unknown,tags:unknown):CapabilityName[]{const set=new Set<CapabilityName>(CAPABILITY_MAP[String(category??'')]??[]);for(const t of(Array.isArray(tags)?tags:[]).map(String)){if(t.includes('coding'))set.add('coding');if(t.includes('debug'))set.add('debugging');if(t.includes('safety')||t.includes('refus'))set.add('safety');if(t.includes('adv'))set.add('adversarialRobustness');if(t.includes('long'))set.add('longContext');if(t.includes('loc'))set.add('localization');}return[...set];}
function upstreamTier(t:string):Scenario['tier']{return t==='very_hard'?'very-hard':t as Scenario['tier'];}
function normalizeScoring(v:unknown):Scenario['scoring']|undefined{return v&&typeof v==='object'?v as Scenario['scoring']:undefined;}
interface RawExpectedCall { tool?: string; name?: string; args?: Record<string, unknown>; arguments?: Record<string, unknown>; required?: boolean; returns?: unknown; error?: string; }
export interface RawUpstreamScenario { id?: string; tier?: string; category?: string; title?: string; domain?: 'generic' | 'quant' | 'dev_ops'; description?: string; prompt?: string; system_prompt?: string; tools?: unknown; expected_tool_calls?: RawExpectedCall[]; expected_text?: string; difficulty?: number; tags?: unknown; constraints?: unknown; budget?: { max_tool_calls?: number; max_turns?: number; timeout_seconds?: number }; tool_responses?: Record<string, import('./types.js').ToolResponseRule[]>; scoring?: Scenario['scoring']; context_prefill_tokens?: number; context_prefill_template?: string; ranking_dimensions?: Dimension[]; }
interface UpstreamManifestRecord { scenario: RawUpstreamScenario; }
interface UpstreamManifest { records?: UpstreamManifestRecord[]; }
function expectedCalls(raw: RawUpstreamScenario): Scenario['expectedToolCalls']{const list=Array.isArray(raw.expected_tool_calls)?raw.expected_tool_calls:[];return list.map((c: RawExpectedCall)=>({name:String(c.tool??c.name),arguments:(c.args??c.arguments??{}) as Record<string,unknown>,required:c.required!==false,toolResult:c.returns,errorResult:c.error}));}
export function convertUpstreamScenario(raw: RawUpstreamScenario):Scenario{const b=raw.budget??{};return{id:String(raw.id),version:'1.0.0',tier:upstreamTier(String(raw.tier)),category:String(raw.category??'unknown'),title:raw.title,domain:raw.domain,description:String(raw.description??raw.title??raw.id),prompt:String(raw.prompt??''),systemPrompt:raw.system_prompt,tools:toolDefinitions(raw.tools),expectedToolCalls:expectedCalls(raw),expectedText:raw.expected_text,difficulty:Number(raw.difficulty??0),capabilities:capabilities(raw.category,raw.tags),constraints:Array.isArray(raw.constraints)?raw.constraints.map(String):[],tags:Array.isArray(raw.tags)?raw.tags.map(String):[],budget:{maxToolCalls:Number(b.max_tool_calls??64),maxTurns:Number(b.max_turns??8),timeoutSeconds:Number(b.timeout_seconds??40)},toolResponses:raw.tool_responses,scoring:normalizeScoring(raw.scoring),contextPrefillTokens:raw.context_prefill_tokens,contextPrefillTemplate:raw.context_prefill_template,rankingDimensions:Array.isArray(raw.ranking_dimensions)?raw.ranking_dimensions:[]};}
export async function loadUpstreamScenarios(dir=process.env.TOOLERY_UPSTREAM_DIR??path.resolve('vendor/toolery-upstream')):Promise<Scenario[]>{const files=(await readdir(dir)).filter(f=>/\.ya?ml$/.test(f)).sort();if(files.length!==143)throw new Error(`Expected 143 upstream scenario files in ${dir}, found ${files.length}. Run npm run sync:upstream.`);const out=await Promise.all(files.map(async f=>convertUpstreamScenario(yaml.parse(await readFile(path.join(dir,f),'utf8')) as RawUpstreamScenario)));if(new Set(out.map(s=>s.id)).size!==143)throw new Error('Upstream scenario IDs are not unique.');return out;}
export function loadUpstreamScenariosSync(dir=process.env.TOOLERY_UPSTREAM_DIR??path.resolve('vendor/toolery-upstream')):Scenario[]{const manifestPath=path.resolve(dir,'manifest.json');if(!existsSync(manifestPath))throw new Error(`Upstream scenario pack is not synced (missing ${manifestPath}). Run 'npm run sync:upstream' on a networked machine, or use --source synthetic.`);const manifest=JSON.parse(readSync(manifestPath,'utf8')) as UpstreamManifest;if(!Array.isArray(manifest.records)||manifest.records.length!==143)throw new Error('Invalid upstream manifest; expected 143 scenarios. Run npm run sync:upstream.');return manifest.records.map((r: UpstreamManifestRecord)=>convertUpstreamScenario(r.scenario));}
export function loadUpstreamFromManifest(manifest: UpstreamManifest | unknown):Scenario[]{const m=manifest as UpstreamManifest|undefined;if(!m||!Array.isArray(m.records)||m.records.length!==143)throw new Error('Invalid upstream manifest; expected 143 records.');return m.records.map((r: UpstreamManifestRecord)=>convertUpstreamScenario(r.scenario));}
