import {readFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import yaml from 'yaml';
import {toolByName} from './tool-catalog.js';
import type {CapabilityName,JsonSchema,Scenario,ScenarioCheck,ToolDefinition} from './types.js';

export const UPSTREAM_SOURCE='karolpalys/toolery@36c8c0c217898aade7500fa13b02fdc4d58899f7';
const CAPABILITY_MAP:Record<string,CapabilityName[]>={
  tool_selection:['toolSelection'],parameter_precision:['parameterPrecision'],multi_step_chains:['agenticPlanning'],restraint_refusal:['restraint'],error_recovery:['errorRecovery'],structured_reasoning:['agenticPlanning'],instruction_following:['instructionFollowing'],context_state_tracking:['stateTracking'],coding:['coding'],debugging:['debugging'],safety_boundaries:['safety'],adversarial_robustness:['adversarialRobustness'],toolset_scale:['toolSelection'],autonomous_planning:['agenticPlanning'],creative_composition:['structuredOutput'],structured_output:['structuredOutput'],hallucination:['calibration','correctness'],terminal_handling:['terminalHandling'],
};
function schema():JsonSchema{return{type:'object',properties:{},additionalProperties:true};}
function toolDefinitions(names:unknown):ToolDefinition[]{return(Array.isArray(names)?names:[]).map(name=>{const n=String(name);const known=toolByName.get(n);return known??{name:n,description:`Upstream Toolery benchmark fixture tool: ${n}.`,parameters:schema()};});}
function capabilities(category:unknown,tags:unknown):CapabilityName[]{const set=new Set<CapabilityName>();for(const c of CAPABILITY_MAP[String(category??'') ]??[])set.add(c);for(const t of(Array.isArray(tags)?tags:[]).map(String)){if(t.includes('coding'))set.add('coding');if(t.includes('debug'))set.add('debugging');if(t.includes('safety')||t.includes('refus'))set.add('safety');if(t.includes('adv'))set.add('adversarialRobustness');if(t.includes('long'))set.add('longContext');if(t.includes('loc'))set.add('localization');}return [...set];}
function upstreamTier(t:string):Scenario['tier']{return t==='very_hard'?'very-hard':t as Scenario['tier'];}
function normalizeScoring(value:unknown):Scenario['scoring']|undefined{return value&&typeof value==='object'?value as Scenario['scoring']:undefined;}
function expectedCalls(raw:any):Scenario['expectedToolCalls']{const list=Array.isArray(raw.expected_tool_calls)?raw.expected_tool_calls:[];return list.map((c:any)=>({name:String(c.tool??c.name),arguments:(c.args??c.arguments??{}) as Record<string,unknown>,required:c.required!==false,toolResult:c.returns,errorResult:c.error}));}
export function convertUpstreamScenario(raw:any):Scenario{const budget=raw.budget??{};const checks=(raw.scoring?.required??[]).concat(raw.scoring?.forbidden??[]).concat(raw.scoring?.partial??[]) as ScenarioCheck[];return{id:String(raw.id),version:'1.0.0',tier:upstreamTier(String(raw.tier)),category:String(raw.category??'unknown'),title:raw.title,domain:raw.domain,description:String(raw.description??raw.title??raw.id),prompt:String(raw.prompt??''),systemPrompt:raw.system_prompt,tools:toolDefinitions(raw.tools),expectedToolCalls:expectedCalls(raw),expectedText:raw.expected_text,difficulty:raw.difficulty??0,capabilities:capabilities(raw.category,raw.tags),constraints:Array.isArray(raw.constraints)?raw.constraints.map(String):[],tags:Array.isArray(raw.tags)?raw.tags.map(String):[],budget:{maxToolCalls:Number(budget.max_tool_calls??64),maxTurns:Number(budget.max_turns??8),timeoutSeconds:Number(budget.timeout_seconds??40)},toolResponses:raw.tool_responses,scoring:normalizeScoring(raw.scoring),contextPrefillTokens:raw.context_prefill_tokens,contextPrefillTemplate:raw.context_prefill_template,rankingDimensions:Array.isArray(raw.ranking_dimensions)?raw.ranking_dimensions.map(String):[]};}
export async function loadUpstreamScenarios(dir=process.env.TOOLERY_UPSTREAM_DIR??path.resolve('vendor/toolery-upstream')):Promise<Scenario[]>{const files=(await readdir(dir)).filter(f=>f.endsWith('.yaml')||f.endsWith('.yml')).sort();if(files.length!==143)throw new Error(`Expected 143 upstream scenario files in ${dir}, found ${files.length}. Run npm run sync:upstream.`);const out:Scenario[]=[];for(const f of files){const raw=yaml.parse(await readFile(path.join(dir,f),'utf8'));out.push(convertUpstreamScenario(raw));}const ids=new Set(out.map(s=>s.id));if(ids.size!==143)throw new Error('Upstream scenario IDs are not unique.');return out;}
export function loadUpstreamFromManifest(manifest:any):Scenario[]{if(!manifest||!Array.isArray(manifest.records)||manifest.records.length!==143)throw new Error('Invalid upstream manifest; expected 143 records.');return manifest.records.map((record:any)=>convertUpstreamScenario(record.scenario));}
